export function courseRecommentationList() {
  const reList = [
    {
      title: "Master of Professional Accounting",
      UniName: "UNSW Sydney - University of New South Wales",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_339139.jpg",
    },
    {
      title: "Bachelor of Physiotherapy (Honours)",
      UniName: "University of Newcastle",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_293343.jpg",
    },
    {
      title: "Master of Urban and Regional Planning",
      UniName: "University of South Australia (UniSA)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_290701.jpg",
    },
    {
      title: "Master of Information Systems",
      UniName: "University of Southern Queensland (UniSQ)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_339139.jpg",
    },
    {
      title: "Master of Professional Accounting (Extension)",
      UniName: "University of Technology Sydney - UTS",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_257235.jpg",
    },
    {
      title: "Master of Urban and Regional Planning",
      UniName: "University of South Australia (UniSA)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_290701.jpg",
    },
    {
      title: "Master of Information Systems",
      UniName: "University of Southern Queensland (UniSQ)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_339139.jpg",
    },
    {
      title: "Master of Urban and Regional Planning",
      UniName: "University of South Australia (UniSA)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_290701.jpg",
    },
    {
      title: "Bachelor of Physiotherapy (Honours)",
      UniName: "University of Newcastle",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_293343.jpg",
    },
    {
      title: "Master of Urban and Regional Planning",
      UniName: "University of South Australia (UniSA)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_290701.jpg",
    },
    {
      title: "Master of Information Systems",
      UniName: "University of Southern Queensland (UniSQ)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_339139.jpg",
    },
    {
      title: "Master of Urban and Regional Planning",
      UniName: "University of South Australia (UniSA)",
      logoUrl:
        "https://images-intl.prod.aws.idp-connect.com/commimg/myhotcourses/institution/myhc_290701.jpg",
    },
  ];

  return reList;
}

export function getSubjects() {
  const subjectList = [
    {
      id: 1,
      group: "Agriculture and Veterinary Medicine",
      value: "Agriculture",
      checked: false,
    },
    {
      id: 3,
      group: "Agriculture and Veterinary Medicine",
      value: "Farm Management",
      checked: false,
    },
    {
      id: 4,
      group: "Agriculture and Veterinary Medicine",
      value: "Horticulture",
      checked: false,
    },
    {
      id: 5,
      group: "Agriculture and Veterinary Medicine",
      value: "Plant and Crop Sciences",
      checked: false,
    },
    {
      id: 2,
      group: "Agriculture and Veterinary Medicine",
      value: "Veterinary Medicine",
      checked: false,
    },
    {
      id: 8,
      group: "Applied and Pure Sciences",
      value: "Astronomy",
      checked: false,
    },
    {
      id: 9,
      group: "Applied and Pure Sciences",
      value: "Biology",
      checked: false,
    },
    {
      id: 11,
      group: "Applied and Pure Sciences",
      value: "Biomedical Sciences",
      checked: false,
    },
    {
      id: 6,
      group: "Applied and Pure Sciences",
      value: "Chemistry",
      checked: false,
    },
    {
      id: 15,
      group: "Applied and Pure Sciences",
      value: "Earth Sciences",
      checked: false,
    },
    {
      id: 16,
      group: "Applied and Pure Sciences",
      value: "Environmental Sciences",
      checked: false,
    },
    {
      id: 7,
      group: "Applied and Pure Sciences",
      value: "Food Science and Technology",
      checked: false,
    },
    {
      id: 14,
      group: "Applied and Pure Sciences",
      value: "Forensic science",
      checked: false,
    },
    {
      id: 13,
      group: "Applied and Pure Sciences",
      value: "General Sciences",
      checked: false,
    },
    {
      id: 18,
      group: "Applied and Pure Sciences",
      value: "Life Sciences",
      checked: false,
    },
    {
      id: 10,
      group: "Applied and Pure Sciences",
      value: "Materials Sciences",
      checked: false,
    },
    {
      id: 12,
      group: "Applied and Pure Sciences",
      value: "Mathematics",
      checked: false,
    },
    {
      id: 17,
      group: "Applied and Pure Sciences",
      value: "Physical Geography",
      checked: false,
    },
    {
      id: 19,
      group: "Applied and Pure Sciences",
      value: "Physics",
      checked: false,
    },
    {
      id: 20,
      group: "Applied and Pure Sciences",
      value: "Sports Science",
      checked: false,
    },
    {
      id: 21,
      group: "Architecture and Construction",
      value: "Architecture",
      checked: false,
    },
    {
      id: 24,
      group: "Architecture and Construction",
      value: "Built Environment",
      checked: false,
    },
    {
      id: 23,
      group: "Architecture and Construction",
      value: "Construction",
      checked: false,
    },
    {
      id: 25,
      group: "Architecture and Construction",
      value: "Maintenance Services",
      checked: false,
    },
    {
      id: 26,
      group: "Architecture and Construction",
      value: "Planning",
      checked: false,
    },
    {
      id: 27,
      group: "Architecture and Construction",
      value: "Property Management",
      checked: false,
    },
    {
      id: 22,
      group: "Architecture and Construction",
      value: "Surveying",
      checked: false,
    },
    {
      id: 28,
      group: "Business and Management",
      value: "Accounting",
      checked: false,
    },
    {
      id: 33,
      group: "Business and Management",
      value: "Business Studies",
      checked: false,
    },
    {
      id: 34,
      group: "Business and Management",
      value: "E-Commerce",
      checked: false,
    },
    {
      id: 32,
      group: "Business and Management",
      value: "Entrepreneurship",
      checked: false,
    },
    {
      id: 35,
      group: "Business and Management",
      value: "Finance",
      checked: false,
    },
    {
      id: 36,
      group: "Business and Management",
      value: "Human Resource Management",
      checked: false,
    },
    {
      id: 37,
      group: "Business and Management",
      value: "Management",
      checked: false,
    },
    {
      id: 38,
      group: "Business and Management",
      value: "Marketing",
      checked: false,
    },
    {
      id: 29,
      group: "Business and Management",
      value: "Office Administration",
      checked: false,
    },
    {
      id: 30,
      group: "Business and Management",
      value: "Quality Management",
      checked: false,
    },
    {
      id: 39,
      group: "Business and Management",
      value: "Retail",
      checked: false,
    },
    {
      id: 31,
      group: "Business and Management",
      value: "Transportation and Logistics",
      checked: false,
    },
    {
      id: 40,
      group: "Computer Science and IT",
      value: "Computer Science",
      checked: false,
    },
    {
      id: 43,
      group: "Computer Science and IT",
      value: "Computing",
      checked: false,
    },
    { id: 41, group: "Computer Science and IT", value: "IT", checked: false },
    {
      id: 42,
      group: "Computer Science and IT",
      value: "Multimedia",
      checked: false,
    },
    {
      id: 44,
      group: "Computer Science and IT",
      value: "Software",
      checked: false,
    },
    { id: 45, group: "Creative Arts and Design", value: "Art", checked: false },
    {
      id: 54,
      group: "Creative Arts and Design",
      value: "Art Administration",
      checked: false,
    },
    {
      id: 53,
      group: "Creative Arts and Design",
      value: "Crafts",
      checked: false,
    },
    {
      id: 49,
      group: "Creative Arts and Design",
      value: "Dance",
      checked: false,
    },
    {
      id: 50,
      group: "Creative Arts and Design",
      value: "Fashion and Textile Design",
      checked: false,
    },
    {
      id: 47,
      group: "Creative Arts and Design",
      value: "Graphic Design",
      checked: false,
    },
    {
      id: 46,
      group: "Creative Arts and Design",
      value: "Industrial Design",
      checked: false,
    },
    {
      id: 55,
      group: "Creative Arts and Design",
      value: "Interior Design",
      checked: false,
    },
    {
      id: 51,
      group: "Creative Arts and Design",
      value: "Music",
      checked: false,
    },
    {
      id: 48,
      group: "Creative Arts and Design",
      value: "Non-industrial Design",
      checked: false,
    },
    {
      id: 52,
      group: "Creative Arts and Design",
      value: "Theatre and Drama Studies",
      checked: false,
    },
    {
      id: 147,
      group: "Education and Training",
      value: "Adult Education",
      checked: false,
    },
    { id: 142, group: "Education and Training", value: "CPD", checked: false },
    {
      id: 151,
      group: "Education and Training",
      value: "Career Advice",
      checked: false,
    },
    {
      id: 146,
      group: "Education and Training",
      value: "Childhood Education",
      checked: false,
    },
    {
      id: 149,
      group: "Education and Training",
      value: "Coaching",
      checked: false,
    },
    {
      id: 140,
      group: "Education and Training",
      value: "Education Learning",
      checked: false,
    },
    {
      id: 145,
      group: "Education and Training",
      value: "Education Management",
      checked: false,
    },
    {
      id: 141,
      group: "Education and Training",
      value: "Education Research",
      checked: false,
    },
    {
      id: 143,
      group: "Education and Training",
      value: "Educational Psychology",
      checked: false,
    },
    {
      id: 144,
      group: "Education and Training",
      value: "Pedagogy",
      checked: false,
    },
    {
      id: 152,
      group: "Education and Training",
      value: "Special Education",
      checked: false,
    },
    {
      id: 150,
      group: "Education and Training",
      value: "Specialised Teaching",
      checked: false,
    },
    {
      id: 148,
      group: "Education and Training",
      value: "Teacher Training / PGCE",
      checked: false,
    },
    {
      id: 64,
      group: "Engineering",
      value: "Aerospace Engineering",
      checked: false,
    },
    {
      id: 73,
      group: "Engineering",
      value: "Biomedical Engineering",
      checked: false,
    },
    {
      id: 69,
      group: "Engineering",
      value: "Chemical and Materials Engineering",
      checked: false,
    },
    {
      id: 56,
      group: "Engineering",
      value: "Civil Engineering",
      checked: false,
    },
    {
      id: 70,
      group: "Engineering",
      value: "Electrical Engineering",
      checked: false,
    },
    {
      id: 72,
      group: "Engineering",
      value: "Electronic Engineering",
      checked: false,
    },
    {
      id: 63,
      group: "Engineering",
      value: "Environmental Engineering",
      checked: false,
    },
    {
      id: 61,
      group: "Engineering",
      value: "General Engineering and Technology",
      checked: false,
    },
    {
      id: 67,
      group: "Engineering",
      value: "Manufacturing and Production",
      checked: false,
    },
    {
      id: 65,
      group: "Engineering",
      value: "Marine Engineering",
      checked: false,
    },
    {
      id: 71,
      group: "Engineering",
      value: "Mechanical Engineering",
      checked: false,
    },
    { id: 58, group: "Engineering", value: "Metallurgy", checked: false },
    {
      id: 57,
      group: "Engineering",
      value: "Mining and Oil & Gas Operations",
      checked: false,
    },
    {
      id: 62,
      group: "Engineering",
      value: "Power and Energy Engineering",
      checked: false,
    },
    { id: 60, group: "Engineering", value: "Quality Control", checked: false },
    {
      id: 68,
      group: "Engineering",
      value: "Structural Engineering",
      checked: false,
    },
    {
      id: 59,
      group: "Engineering",
      value: "Telecommunications",
      checked: false,
    },
    {
      id: 66,
      group: "Engineering",
      value: "Vehicle Engineering",
      checked: false,
    },
    {
      id: 74,
      group: "Health and Medicine",
      value: "Complementary Health",
      checked: false,
    },
    {
      id: 75,
      group: "Health and Medicine",
      value: "Counselling",
      checked: false,
    },
    {
      id: 82,
      group: "Health and Medicine",
      value: "Dentistry",
      checked: false,
    },
    {
      id: 87,
      group: "Health and Medicine",
      value: "Health Studies",
      checked: false,
    },
    {
      id: 88,
      group: "Health and Medicine",
      value: "Health and Safety",
      checked: false,
    },
    { id: 83, group: "Health and Medicine", value: "Medicine", checked: false },
    {
      id: 78,
      group: "Health and Medicine",
      value: "Midwifery",
      checked: false,
    },
    { id: 85, group: "Health and Medicine", value: "Nursing", checked: false },
    {
      id: 77,
      group: "Health and Medicine",
      value: "Nutrition and Health",
      checked: false,
    },
    {
      id: 86,
      group: "Health and Medicine",
      value: "Ophthalmology",
      checked: false,
    },
    {
      id: 84,
      group: "Health and Medicine",
      value: "Pharmacology",
      checked: false,
    },
    {
      id: 79,
      group: "Health and Medicine",
      value: "Physiology",
      checked: false,
    },
    {
      id: 81,
      group: "Health and Medicine",
      value: "Physiotherapy",
      checked: false,
    },
    {
      id: 76,
      group: "Health and Medicine",
      value: "Psychology",
      checked: false,
    },
    {
      id: 80,
      group: "Health and Medicine",
      value: "Public Health",
      checked: false,
    },
    { id: 89, group: "Humanities", value: "Archaeology", checked: false },
    { id: 91, group: "Humanities", value: "Classics", checked: false },
    { id: 92, group: "Humanities", value: "Cultural Studies", checked: false },
    { id: 96, group: "Humanities", value: "English Studies", checked: false },
    { id: 94, group: "Humanities", value: "General Studies", checked: false },
    { id: 95, group: "Humanities", value: "History", checked: false },
    { id: 97, group: "Humanities", value: "Languages", checked: false },
    { id: 98, group: "Humanities", value: "Literature", checked: false },
    { id: 93, group: "Humanities", value: "Museum Studies", checked: false },
    { id: 99, group: "Humanities", value: "Philosophy", checked: false },
    { id: 90, group: "Humanities", value: "Regional Studies", checked: false },
    {
      id: 100,
      group: "Humanities",
      value: "Religious Studies",
      checked: false,
    },
    { id: 103, group: "Law", value: "Civil Law", checked: false },
    { id: 104, group: "Law", value: "Criminal Law", checked: false },
    { id: 102, group: "Law", value: "International Law", checked: false },
    { id: 106, group: "Law", value: "Legal Advice", checked: false },
    { id: 101, group: "Law", value: "Legal Studies", checked: false },
    { id: 105, group: "Law", value: "Public Law", checked: false },
    { id: 107, group: "MBA", value: "test Subject", checked: false },
    {
      id: 137,
      group: "Personal Care and Fitness",
      value: "Aromatherapy",
      checked: false,
    },
    {
      id: 134,
      group: "Personal Care and Fitness",
      value: "Beauty Therapy",
      checked: false,
    },
    {
      id: 135,
      group: "Personal Care and Fitness",
      value: "Hairdressing",
      checked: false,
    },
    {
      id: 133,
      group: "Personal Care and Fitness",
      value: "Health and Fitness",
      checked: false,
    },
    {
      id: 139,
      group: "Personal Care and Fitness",
      value: "Massage",
      checked: false,
    },
    {
      id: 138,
      group: "Personal Care and Fitness",
      value: "Reflexology",
      checked: false,
    },
    {
      id: 136,
      group: "Personal Care and Fitness",
      value: "Therapeutic",
      checked: false,
    },
    {
      id: 108,
      group: "Social Studies and Media",
      value: "Anthropology",
      checked: false,
    },
    {
      id: 120,
      group: "Social Studies and Media",
      value: "Economics",
      checked: false,
    },
    {
      id: 119,
      group: "Social Studies and Media",
      value: "Environmental Management",
      checked: false,
    },
    {
      id: 121,
      group: "Social Studies and Media",
      value: "Film & Television",
      checked: false,
    },
    {
      id: 113,
      group: "Social Studies and Media",
      value: "Human Geography",
      checked: false,
    },
    {
      id: 118,
      group: "Social Studies and Media",
      value: "International Development",
      checked: false,
    },
    {
      id: 117,
      group: "Social Studies and Media",
      value: "International relations",
      checked: false,
    },
    {
      id: 122,
      group: "Social Studies and Media",
      value: "Journalism",
      checked: false,
    },
    {
      id: 123,
      group: "Social Studies and Media",
      value: "Library Studies",
      checked: false,
    },
    {
      id: 114,
      group: "Social Studies and Media",
      value: "Linguistics",
      checked: false,
    },
    {
      id: 124,
      group: "Social Studies and Media",
      value: "Media",
      checked: false,
    },
    {
      id: 110,
      group: "Social Studies and Media",
      value: "Photography",
      checked: false,
    },
    {
      id: 125,
      group: "Social Studies and Media",
      value: "Politics",
      checked: false,
    },
    {
      id: 116,
      group: "Social Studies and Media",
      value: "Public Administration",
      checked: false,
    },
    {
      id: 112,
      group: "Social Studies and Media",
      value: "Social Sciences",
      checked: false,
    },
    {
      id: 115,
      group: "Social Studies and Media",
      value: "Social Work",
      checked: false,
    },
    {
      id: 109,
      group: "Social Studies and Media",
      value: "Sociology",
      checked: false,
    },
    {
      id: 111,
      group: "Social Studies and Media",
      value: "Writing",
      checked: false,
    },
    {
      id: 132,
      group: "Travel and Hospitality",
      value: "Aviation",
      checked: false,
    },
    {
      id: 126,
      group: "Travel and Hospitality",
      value: "Catering",
      checked: false,
    },
    {
      id: 129,
      group: "Travel and Hospitality",
      value: "Food and Drink Production",
      checked: false,
    },
    {
      id: 131,
      group: "Travel and Hospitality",
      value: "Hospitality",
      checked: false,
    },
    {
      id: 130,
      group: "Travel and Hospitality",
      value: "Hotel Management",
      checked: false,
    },
    {
      id: 128,
      group: "Travel and Hospitality",
      value: "Leisure Management",
      checked: false,
    },
    {
      id: 127,
      group: "Travel and Hospitality",
      value: "Travel and Tourism",
      checked: false,
    },
  ];

  return subjectList;
}
